### salvar
POST http://localhost:8080/clientes
Content-Type: application/json

< ./post-michael-jordan.json

### listar
GET http://localhost:8080/clientes

### atualizar
PUT http://localhost:8080/clientes/63fd3cad9d7ede7a435db211s
Content-Type: application/json

< ./post-michael-jordan.json

### remover
DELETE http://localhost:8080/clientes/63fd384cf4727d6f5746ff6d
